### ISSUE TITLE
Review current code

### ISSUE THREAD

**Issue by shadowhand** [middlewares/request-handler#1]
@oscarotero are you satisfied with this approach?

Refs middlewares/fast-route#6

**Comment by oscarotero** [comment]
Yes, it's ok.
I only suggest to improve the README with a full example of how this middleware should work with other (like fast-route). And the same in the README of fast-route, in order to be clear about the scope of the middleware and that this middleware does nothing alone.

**Comment by oscarotero** [comment]
FYI, I did something like that here: https://github.com/middlewares/image-manipulation#example

**Comment by oscarotero** [comment]
And please, change the description of the middleware in the readme. Currently says `Middleware to use FastRoute.`

**Comment by mindplay-dk** [comment]
Honestly, I don't get it.

There is precisely zero lines of code in there that actually do something - this class literally delegates 100% of the work to other components.

Why would you need/want to dispatch in such a round-about way?

It's almost completely dependent on other components, and hides it's dependencies on those components - it's not obvious what it does at all, perhaps because (sorry, but) it's not really doing anything at all?

I'd prefer just writing those 1-2 lines of code to dispatch router/handler.

**Comment by shadowhand** [comment]
@mindplay-dk the problem, as I see it, is there are two completely separate steps when it comes to route handing:

1. Determining if the request URI is valid and can be resolved by the application.
2. Handling the request inside the application.

There are a number of things that can happen between the first and second steps. Most importantly authentication and authorization. There is, in my opinion, absolutely no reason to trigger auth errors for requests that will ultimately fail to resolve (404/405 status). Typically these auth steps will involve additional resources such as database access, which means that bad requests will still be using server resources that will be "thrown away" when the request fails to resolve to a handler. In my case, this is a non-trivial amount of database access (db is non local, so network traffic is involved too) and it has a significant impact on response times for bad requests. Enough that a bad client could actually impact load times for legitimate requests.

Secondly, the routing is a separate concern from request handling. Any routing system will eventually resolve to some kind of code call. By splitting routing from request handling, we can reuse this middleware with any routing component, such as [aura-router](https://github.com/middlewares/aura-router).

**Comment by shadowhand** [comment]
@oscarotero updated README with a complete example.

**Comment by oscarotero** [comment]
One more thing. I usually use the `->attribute()` method to define the attribute name used to store values by the middleware, like does client-ip or fast-route. But to consume these attributes, I use a more descriptive name. For example, both [access-log](https://github.com/middlewares/access-log) and [firewall](https://github.com/middlewares/firewall) has the `ipAttribute()` method, to configure the attribute name used to get the ip. The general rule (in my mind) is that a middleware should set just one attribute, but can get values from various attributes, so this naming style allows that.
I suggest to rename the `attribute()` method to, for example `handlerAttribute()`

**Comment by oscarotero** [comment]
Ok, I've released a new version with the doc improvements and renamed `attribute()` to `handlerAttribute()` (sorry if this breaks something, but I think it's important to keep naming consistency).

I close this, thanks for this good work.

**Comment by itsjavi** [comment]
I would also update the README explaining the use cases why this approach could be useful like @shadowhand described very well. Only with the current README and the src code I was also confused about the purpose of this middleware.

**Comment by oscarotero** [comment]
@itsjavi The understanding of this is important. Do you mind to do a pull request with the improved README?
Thanks

**Comment by itsjavi** [comment]
I'll do that @oscarotero .

Another suggestion: why not renaming `attribute()` to `setAttribute()` and then having the `getAttribute()` method name consistent in every middleware? This way we won't need to give it a different name every time.
In case a middleware needs more than one attribute, one option (more an implementation detail) is to use `getAttribute()` as the base name of the new ones.

**Comment by oscarotero** [comment]
@itsjavi Thanks.
There's no `get/set` methods to define options in any other middleware. All methods are "setters" (attribute, arguments, etc) and even the `getAttribute()` that you're proposing is really a setter (you're setting the key name used to get the atribute).
This naming convention was choosen for simplicity (all methods are setters and returns the middleware instance, allowing chaining).
