### ISSUE TITLE
PHPUnit: Prophecy - failing build

### ISSUE THREAD

**Issue by solcik** [middlewares/request-handler#12]
@oscarotero the build is failing just because of the new dependency `phpspec/prophecy-phpunit`, which I added - because of new PHPUnit deprecated calling `prophesize` and suggests to install this package and use Trait from it.

https://github.com/middlewares/request-handler/blob/master/tests/RequestHandlerTest.php#L23
https://github.com/middlewares/request-handler/blob/master/tests/RequestHandlerTest.php#L82

**Comment by oscarotero** [comment]
Yes, I know.

The problem is that this package fails in php 7.2, so finally I decided to remove the test that was using this functionality, because it's just a small test case, not very important for not. It can be added later
