### ISSUE TITLE
Closure/callable from router isn't supported ?

### ISSUE THREAD

**Issue by ncou** [middlewares/request-handler#5]
Hi,

I looked at the fastroute & aurarouter middleware and they both claim you can add a handler as a closure, callable, controller...Etc :

`FastRoute allows anything to be defined as the router handler (a closure, callback, action object, controller class, etc). The middleware will store this handler in a request attribute.`

But in your middleware requestHandler, the handler retrieved in the request can only be a typeof middlewareinterface or requesthandlerinterface or a string (a key to search in the container), but if the handler is of type : closure or callable, then this middleware will not be working (no handler execution).

you explain me why this possibility is not present ? thank you.

Keep up the good work.

**Comment by oscarotero** [comment]
Hi
That feature was removed in the lastest version for the sake of typeness. A callable can have any signature and can return any value, and the inclusion of the RequestHandlerInterface in the latest version of PSR-15 provides a cleaner way to handle requests.

Anyway, this is the second time that this topic arises (https://github.com/middlewares/request-handler/pull/4) so I might consider reintroduce support for callables.

**Comment by oscarotero** [comment]
Ok, finally I've added support for `Closure` in the just released stable version v1.0
