### ISSUE TITLE
Why not delegate to $handler

### ISSUE THREAD

**Issue by franzliedke** [middlewares/request-handler#9]
When no valid attribute is present, the middleware could keep delegating after all... Or is there just no sensible use-case?

Asking because middlewares/base-path-router#3 makes me imagine a situation where the router has dynamic prefixes, but no default handler, it could just delegate to its own handler. Using request-handler as that delegate would then lead to a situation where request-handler would need a fallthrough. Isn't that the best place for the defaultHandler? After all, the router isn't useful without request-handler anyway, so it could just rely on the latter for the default handler.

**Comment by oscarotero** [comment]
[middlewares/filesystem Reader](https://github.com/middlewares/filesystem/blob/master/src/Reader.php#L27) has a `continueOnError()` option to continue to inner middlewares instead return a 404-405 response if the file is not found or the method is not allowed. We can include this option here, due in practice, is like a defaultHandler.

**Comment by oscarotero** [comment]
I just released [v1.3.0](https://github.com/middlewares/request-handler/releases/tag/v1.3.0) with the `continueOnEmpty()` option.
